language: smalltalk
sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

os:
    - linux

smalltalk:
    - Pharo-6.1
    - Pharo64-7.0
    - Pharo64-8.0
    - Pharo64-9.0
